[package]
name = "cmx-traits"
version.workspace = true
edition.workspace = true

[dependencies]
cmx-core = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
extism = "1.4"
