[package]
name = "cmx-utils"
version.workspace = true
edition.workspace = true

[dependencies]
# 序列化框架
serde = { workspace = true }
# JSON 序列化/反序列化
serde_json = { workspace = true }
# Base64 编码/解码
base64 = { workspace = true }
# 错误处理
thiserror = { workspace = true }
# ZIP 压缩/解压
zip = { workspace = true }
# 目录遍历
walkdir = { workspace = true }
# 改进的文件系统操作
fs-err = { workspace = true }
# 随机数生成
rand = { workspace = true }
# AES-256-GCM 对称加密
aes-gcm = { workspace = true }
# 时间处理
time = { workspace = true }
# 唯一标识符  fast-rng，使用更快的随机数生成器来加速 v4 UUID 的生成
uuid = { workspace = true, features = ["v4", "fast-rng"] }
# 配置管理
config = { workspace = true }
# .env 文件加载
dotenvy = { workspace = true }
# 日志追踪
tracing = { workspace = true }
# 内部依赖 - 特征定义
cmx-traits = { workspace = true }

[dev-dependencies]
# 临时文件测试
tempfile = "3"
