[package]
name = "cmx-buffer"
version.workspace = true
edition.workspace = true

[dependencies]
# 内部依赖 - 工具库
cmx-utils = { workspace = true }
# 内部依赖 - 特征定义
cmx-traits = { workspace = true }
# 内部依赖 - 核心库
cmx-core = { workspace = true }
# Redis 客户端
redis = { workspace = true }
# 序列化框架
serde = { workspace = true }
# JSON 序列化/反序列化
serde_json = { workspace = true }
# MessagePack 序列化/反序列化
rmp-serde = { workspace = true }
# 异步运行时
tokio = { workspace = true }
# 日志追踪
tracing = { workspace = true }
# 错误处理
thiserror = { workspace = true }
# 错误处理
anyhow = { workspace = true }
# 时间处理
chrono = { workspace = true }
# 派生宏
derive_more = { workspace = true }
# 异步 trait
async-trait = { workspace = true }
# 唯一标识符
uuid = { workspace = true, features = ["v4"] }
# Futures 工具
futures-util = { workspace = true }
