//! OpenAPI 文档配置模块
//!
//! 提供 OpenAPI 文档的定义和配置

use utoipa::OpenApi;

/// CMX API OpenAPI 文档
#[derive(OpenApi)]
#[openapi(
    info(
        title = "CMX API",
        version = "1.0.0",
        description = "CMX 系统 API 文档",
    ),
    paths(
        // Domain CRUD handlers
        crate::routes::crud_handlers::domain_crud::create,
        crate::routes::crud_handlers::domain_crud::create_many,
        crate::routes::crud_handlers::domain_crud::get,
        crate::routes::crud_handlers::domain_crud::update,
        crate::routes::crud_handlers::domain_crud::update_many,
        crate::routes::crud_handlers::domain_crud::delete,
        crate::routes::crud_handlers::domain_crud::list,
        crate::routes::crud_handlers::domain_crud::page,
        // Application CRUD handlers
        crate::routes::crud_handlers::application_crud::create,
        crate::routes::crud_handlers::application_crud::create_many,
        crate::routes::crud_handlers::application_crud::get,
        crate::routes::crud_handlers::application_crud::update,
        crate::routes::crud_handlers::application_crud::update_many,
        crate::routes::crud_handlers::application_crud::delete,
        crate::routes::crud_handlers::application_crud::list,
        crate::routes::crud_handlers::application_crud::page,
        // Module CRUD handlers
        crate::routes::crud_handlers::module_crud::create,
        crate::routes::crud_handlers::module_crud::create_many,
        crate::routes::crud_handlers::module_crud::get,
        crate::routes::crud_handlers::module_crud::update,
        crate::routes::crud_handlers::module_crud::update_many,
        crate::routes::crud_handlers::module_crud::delete,
        crate::routes::crud_handlers::module_crud::list,
        crate::routes::crud_handlers::module_crud::page,
        crate::handlers::module::handler::module_custom_page,
        // SysDatasource CRUD handlers
        crate::routes::crud_handlers::sys_datasource_crud::get,
        crate::routes::crud_handlers::sys_datasource_crud::list,
        crate::routes::crud_handlers::sys_datasource_crud::page,

        // Domain handlers
        crate::handlers::domain::handler::get_tree,
        crate::handlers::application::handler::application_custom_page,
        // crate::handlers::domain::handler::get_by_name,


        // SysDatasource 自定义 handlers
        crate::handlers::sys_datasource::handler::get_by_db_id,
        crate::handlers::sys_datasource::handler::create_datasource,
        crate::handlers::sys_datasource::handler::update_datasource,
        crate::handlers::sys_datasource::handler::delete_datasource,
        crate::handlers::sys_datasource::handler::test_connection,
        // Plugin handlers
        crate::handlers::plugin::handler::plugin_install,
        crate::handlers::plugin::handler::plugin_uninstall,
        crate::handlers::plugin::handler::plugin_upgrade,
        crate::handlers::plugin::handler::plugin_downgrade,
        crate::handlers::plugin::handler::plugin_list,
        crate::handlers::plugin::handler::plugin_page,
        crate::handlers::plugin::handler::plugin_get,
        crate::handlers::plugin::handler::plugin_deploy,
        crate::handlers::plugin::handler::plugin_exists,
        crate::handlers::plugin::handler::plugin_functions,
        // PluginControl handlers
        // crate::handlers::plugin::control::handler::control_deploy,
        // crate::handlers::plugin::control::handler::control_install,
        // crate::handlers::plugin::control::handler::control_upgrade,
        // crate::handlers::plugin::control::handler::control_downgrade,
        // crate::handlers::plugin::control::handler::control_uninstall,
        // TableMetadata handlers
        crate::handlers::table_metadata::handler::table_metadata_list,
        crate::handlers::table_metadata::handler::table_metadata_page,
        crate::handlers::table_metadata::handler::table_metadata_get_by_id,
        crate::handlers::table_metadata::handler::table_metadata_get_by_name,
        crate::handlers::table_metadata::handler::table_metadata_exists,
        //服务
        crate::handlers::service::handler::service_call,
        crate::handlers::service::handler::execute_service,
        crate::handlers::service::handler::execute_service_by_key,
        // crate::handlers::service::handler::list_services,
        crate::handlers::service::handler::page_services,
        crate::handlers::service::handler::get_service,
        crate::handlers::service::handler::get_services_by_plugin,
        crate::handlers::service::handler::delete_service,
        crate::handlers::service::handler::service_exists,
        crate::handlers::service::handler::get_openapi_spec,

        // Marketplace handlers
        crate::handlers::marketplace::handler::marketplace_plugin_page,
        crate::handlers::marketplace::handler::marketplace_plugin_get_by_id,
        crate::handlers::marketplace::handler::marketplace_plugin_publish,
        crate::handlers::marketplace::handler::marketplace_plugin_update,
        crate::handlers::marketplace::handler::marketplace_plugin_delete,
        crate::handlers::marketplace::handler::marketplace_plugin_version_list,
        crate::handlers::marketplace::handler::marketplace_plugin_version_get_by_id,
        crate::handlers::marketplace::handler::marketplace_plugin_install,
        crate::handlers::marketplace::handler::marketplace_plugin_rate,
        crate::handlers::marketplace::handler::marketplace_plugin_rating_list,
        crate::handlers::marketplace::handler::marketplace_category_list,
        crate::handlers::marketplace::handler::marketplace_trending_list,
        crate::handlers::marketplace::handler::marketplace_plugin_upgrade,
        crate::handlers::marketplace::handler::marketplace_plugin_check_updates,
        crate::handlers::marketplace::handler::marketplace_plugin_download,
        // Storage handlers
        cmx_storage::handler::upload_handler,
        cmx_storage::handler::download_handler,
        cmx_storage::handler::batch_download_handler,
        cmx_storage::handler::file_info_handler,
        cmx_storage::handler::delete_handler,
        cmx_storage::handler::page_handler,
        cmx_storage::handler::presign_download_handler,
        cmx_storage::handler::presign_upload_handler,
        cmx_storage::handler::multipart_init_handler,
        cmx_storage::handler::multipart_part_handler,
        cmx_storage::handler::multipart_complete_handler,
        cmx_storage::handler::multipart_abort_handler,
        // Auth handlers
        crate::handlers::auth::handler::auth_login,
        crate::handlers::auth::handler::auth_refresh,
        crate::handlers::auth::handler::auth_logout,
        crate::handlers::auth::handler::auth_validate,
        crate::handlers::auth::handler::auth_revoke_all,
        // OAuth2 handlers
        crate::handlers::auth::oauth2_handler::oauth2_authorize,
        crate::handlers::auth::oauth2_handler::oauth2_login,
        crate::handlers::auth::oauth2_handler::oauth2_token,
    ),

    components(
        schemas(
            crate::handlers::domain::Domain,
            crate::handlers::domain::DomainForCreate,
            crate::handlers::domain::DomainForUpdate,
            crate::handlers::domain::DomainTreeNodeData,
            crate::TreeNode<crate::handlers::domain::DomainTreeNodeData>,
            crate::handlers::application::Application,
            crate::handlers::application::ApplicationForCreate,
            crate::handlers::application::ApplicationForUpdate,
            crate::handlers::module::Module,
            crate::handlers::module::ModuleForCreate,
            crate::handlers::module::ModuleForUpdate,
            crate::handlers::sys_datasource::SysDatasource,
            crate::handlers::sys_datasource::SysDatasourceForCreate,
            crate::handlers::sys_datasource::SysDatasourceForUpdate,
            crate::handlers::sys_datasource::handler::GetByDbIdParams,
            crate::handlers::sys_datasource::handler::DatasourceUpdatePayload,
            crate::handlers::sys_datasource::handler::DatasourceDeletePayload,
            crate::handlers::plugin::request::PluginInstallRequest,
            crate::handlers::plugin::request::PluginUninstallRequest,
            crate::handlers::plugin::request::PluginUpgradeRequest,
            crate::handlers::plugin::request::PluginDowngradeRequest,
            crate::handlers::plugin::request::PluginSourceRequest,
            crate::handlers::plugin::request::PluginDeployRequest,
            crate::handlers::plugin::request::PluginFunctionsRequest,
            crate::handlers::plugin::response::PluginInfoResponse,
            crate::handlers::plugin::response::PluginListResponse,
            crate::handlers::plugin::response::InstallResponse,
            crate::handlers::plugin::response::UninstallResponse,
            crate::handlers::plugin::response::UpgradeResponse,
            crate::handlers::plugin::response::DowngradeResponse,
            crate::handlers::plugin::response::PluginDeployResponse,
            crate::handlers::plugin::response::PluginFunctionsResponse,
            // PluginControl schemas
            // crate::handlers::plugin::control::request::ControlDeployRequest,
            // crate::handlers::plugin::control::request::ControlInstallRequest,
            // crate::handlers::plugin::control::request::ControlUpgradeRequest,
            // crate::handlers::plugin::control::request::ControlDowngradeRequest,
            // crate::handlers::plugin::control::request::ControlUninstallRequest,
            // crate::handlers::plugin::control::response::ControlActionResponse,
            crate::Pagination,
            // cmx-api service models
            crate::handlers::service::models::FunctionCallRequest,
            crate::handlers::service::models::FunctionCallResponse,
            crate::handlers::service::models::ServiceExecuteRequest,
            crate::handlers::service::models::ServiceExecuteResponse,
            crate::handlers::service::models::ServiceExecutionStep,
            crate::handlers::service::models::ServiceDeleteQuery,
            crate::handlers::service::models::ServiceListItem,
            crate::handlers::service::models::ServiceDetailResponse,
            // Marketplace models
            crate::handlers::marketplace::request::PublishPluginRequest,
            crate::handlers::marketplace::request::UpdateMarketplacePluginRequest,
            crate::handlers::marketplace::request::DeleteMarketplacePluginRequest,
            crate::handlers::marketplace::request::MarketInstallRequest,
            crate::handlers::marketplace::request::RatePluginRequest,
            crate::handlers::marketplace::request::TrendingFilter,
            crate::handlers::marketplace::request::MarketplacePluginFilterDoc,
            crate::handlers::marketplace::request::MarketplacePluginVersionFilterDoc,
            crate::handlers::marketplace::request::MarketplaceRatingFilterDoc,
            crate::handlers::marketplace::response::MarketplacePluginResponse,
            crate::handlers::marketplace::response::MarketplaceVersionResponse,
            crate::handlers::marketplace::response::MarketplacePluginDetailResponse,
            crate::handlers::marketplace::response::MarketInstallResponse,
            crate::handlers::marketplace::response::MarketplaceRatingResponse,
            crate::handlers::marketplace::response::CategoryResponse,
            // Storage schemas
            cmx_storage::types::FileInfo,
            cmx_storage::types::FileQuery,
            cmx_storage::types::FilePage,
            cmx_storage::types::MultipartSession,
            cmx_storage::types::PartInfo,
            cmx_storage::types::PresignUploadResult,
            cmx_storage::types::PresignUploadRequest,
            cmx_storage::handler::ApiResp<cmx_storage::types::FileInfo>,
            cmx_storage::handler::ApiResp<cmx_storage::types::FilePage>,
            cmx_storage::handler::ApiResp<cmx_storage::types::MultipartSession>,
            cmx_storage::handler::ApiResp<cmx_storage::types::PartInfo>,
            cmx_storage::handler::ApiResp<cmx_storage::types::PresignUploadResult>,
            cmx_storage::handler::ApiResp<String>,
            cmx_storage::handler::DownloadQuery,
            cmx_storage::handler::FileInfoQuery,
            cmx_storage::handler::DeleteQuery,
            cmx_storage::handler::BatchDownloadRequest,
            cmx_storage::handler::PresignDownloadRequest,
            cmx_storage::handler::PresignUploadBody,
            cmx_storage::handler::MultipartInitBody,
            cmx_storage::handler::MultipartPartBody,
            cmx_storage::handler::MultipartCompleteBody,
            cmx_storage::handler::MultipartAbortBody,
            // Auth schemas
            crate::handlers::auth::request::LoginRequest,
            crate::handlers::auth::request::RefreshRequest,
            crate::handlers::auth::request::RevokeRequest,
            crate::handlers::auth::request::RevokeAllRequest,
            crate::handlers::auth::request::ValidateRequest,
            crate::handlers::auth::request::ChangePasswordRequest,
            crate::handlers::auth::response::LoginResponse,
            crate::handlers::auth::response::ValidateResponse,
            crate::handlers::auth::response::OnlineCountResponse,
            // OAuth2 schemas
            crate::handlers::auth::oauth2_request::OAuth2LoginRequest,
            crate::handlers::auth::oauth2_request::OAuth2TokenRequest,
            crate::handlers::auth::oauth2_response::OAuth2AuthorizeResponse,
            crate::handlers::auth::oauth2_response::OAuth2LoginResponse,
            crate::handlers::auth::oauth2_response::OAuth2TokenResponse,
        )
    )
)]
pub struct ApiDoc;
