[package]
name = "cmx-api"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
# -- Web 框架
axum={workspace = true}
tower-http = { workspace = true }
tower-cookies = { workspace = true }

# -- 内部依赖
cmx-utils = { workspace = true }
cmx-core = { workspace = true }
cmx-database = { workspace = true }
cmx-metadata = { workspace = true }
cmx-plugin = { workspace = true }
cmx-traits = { workspace = true }
cmx-service = { workspace = true }

# -- 异步
tokio={workspace = true}

# -- 数据处理
sea-query = { workspace = true }
sea-query-binder = { workspace = true }
modql = { workspace = true, features = ["with-sea-query"] }
sqlx = { workspace = true }

# -- Json
serde = { workspace = true }
serde_json = { workspace = true }
serde_with={ workspace = true }

# -- 时间和UUID
# 时间处理
chrono = { workspace = true, features = ["serde"] }
time = { workspace = true }
uuid = { workspace = true ,features = ["v4","fast-rng"]}

# -- 日志和错误处理
tracing ={workspace = true}
derive_more={workspace = true}
thiserror = { workspace = true }

# -- 验证
validator = { workspace = true }

utoipa={workspace = true}
utoipa-swagger-ui={workspace = true}
log = "0.4.29"
#MsgPack编码
rmp-serde = "1.3.1"
