//! `TriggerBindingStore` 的 PG 实现（W3）。
//!
//! 落单表 `cmx_plugin_trigger_binding`（按 `kind` 区分 event/cron/bizhook，subsumes 方案里
//! event/cron 两表草图——同结构合一更简）。DB 纪律与 cmx-plugin 系一致：`execute_sql*` +
//! `SqlParams::DataValues(Vec<DataValue>)`，jsonb 用 `DataValue::Json(String)`。

use async_trait::async_trait;
use chrono::Utc;
use cmx_core::model::cell::DataValue;
use cmx_core::model::data::dataset::{DataSet, Row, Schema};
use cmx_database::{execute_sql, execute_sql_with_params, query_sql_with_params, SqlParams};
use cmx_plugin_trigger::{TriggerBinding, TriggerBindingStore, TriggerKind};
use serde_json::Value;

/// 建表 DDL（幂等）。表前缀 `cmx_plugin_`，无外键，索引替代。
pub const DDL: &[&str] = &[
    r#"CREATE TABLE IF NOT EXISTS cmx_plugin_trigger_binding (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        kind          VARCHAR(16)  NOT NULL,
        trigger_key   VARCHAR(256) NOT NULL,
        plugin_id     VARCHAR(128) NOT NULL,
        function_name VARCHAR(128) NOT NULL,
        tenant_id     VARCHAR(128),
        enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
        filter_expr   TEXT,
        payload_json  JSONB,
        created_at    TIMESTAMPTZ  NOT NULL,
        updated_at    TIMESTAMPTZ  NOT NULL
    )"#,
    "CREATE INDEX IF NOT EXISTS idx_cmx_plugin_trigger_lookup ON cmx_plugin_trigger_binding (kind, trigger_key)",
    "CREATE INDEX IF NOT EXISTS idx_cmx_plugin_trigger_plugin ON cmx_plugin_trigger_binding (plugin_id)",
];

/// PG 触发绑定存储。
#[derive(Clone)]
pub struct PgTriggerBindingStore {
    db_id: String,
}

impl PgTriggerBindingStore {
    pub fn new(db_id: impl Into<String>) -> Self {
        Self { db_id: db_id.into() }
    }

    /// 幂等建表。
    pub async fn ensure_schema(&self) -> Result<(), String> {
        for stmt in DDL {
            execute_sql(&self.db_id, None, stmt)
                .await
                .map_err(|e| format!("建触发绑定表失败: {e}"))?;
        }
        Ok(())
    }

    async fn query(&self, sql: &str, params: Vec<DataValue>) -> Result<DataSet, String> {
        query_sql_with_params(&self.db_id, None, sql, SqlParams::DataValues(params), "trigger_binding")
            .await
            .map_err(|e| format!("查询触发绑定失败: {e}"))
    }
}

#[async_trait]
impl TriggerBindingStore for PgTriggerBindingStore {
    async fn bindings_for(
        &self,
        kind: TriggerKind,
        trigger_key: &str,
        tenant: Option<&str>,
    ) -> Result<Vec<TriggerBinding>, String> {
        // tenant=None → 命中 tenant_id IS NULL 或任意（默认租户宽松匹配）；Some → 该租户 + 无租户共享绑定。
        let (sql, params) = match tenant {
            Some(t) => (
                "SELECT id, kind, trigger_key, plugin_id, function_name, tenant_id, enabled, filter_expr, payload_json \
                 FROM cmx_plugin_trigger_binding \
                 WHERE kind = $1 AND trigger_key = $2 AND enabled = TRUE AND (tenant_id = $3 OR tenant_id IS NULL)",
                vec![
                    DataValue::String(kind_str(kind).into()),
                    DataValue::String(trigger_key.into()),
                    DataValue::String(t.into()),
                ],
            ),
            None => (
                "SELECT id, kind, trigger_key, plugin_id, function_name, tenant_id, enabled, filter_expr, payload_json \
                 FROM cmx_plugin_trigger_binding \
                 WHERE kind = $1 AND trigger_key = $2 AND enabled = TRUE",
                vec![
                    DataValue::String(kind_str(kind).into()),
                    DataValue::String(trigger_key.into()),
                ],
            ),
        };
        let ds = self.query(sql, params).await?;
        Ok(rows_to_bindings(&ds))
    }

    async fn list_by_kind(&self, kind: TriggerKind) -> Result<Vec<TriggerBinding>, String> {
        let ds = self
            .query(
                "SELECT id, kind, trigger_key, plugin_id, function_name, tenant_id, enabled, filter_expr, payload_json \
                 FROM cmx_plugin_trigger_binding WHERE kind = $1 ORDER BY id",
                vec![DataValue::String(kind_str(kind).into())],
            )
            .await?;
        Ok(rows_to_bindings(&ds))
    }

    async fn save(&self, b: &TriggerBinding) -> Result<i64, String> {
        let now = Utc::now();
        let payload = b
            .payload_json
            .as_ref()
            .map(|v| DataValue::Json(v.to_string()))
            // jsonb 列的 NULL 必须带类型标记，否则 PG 报 "is of type jsonb but expression is of type text"。
            .unwrap_or(DataValue::NullTyped(cmx_core::model::cell::SqlTypeMarker::Json));
        if b.id == 0 {
            let ds = self
                .query(
                    "INSERT INTO cmx_plugin_trigger_binding \
                     (kind, trigger_key, plugin_id, function_name, tenant_id, enabled, filter_expr, payload_json, created_at, updated_at) \
                     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$9) RETURNING id",
                    vec![
                        DataValue::String(kind_str(b.kind).into()),
                        DataValue::String(b.trigger_key.clone()),
                        DataValue::String(b.plugin_id.clone()),
                        DataValue::String(b.function_name.clone()),
                        opt_str(&b.tenant_id),
                        DataValue::Bool(b.enabled),
                        opt_str(&b.filter_expr),
                        payload,
                        DataValue::DateTime(now),
                    ],
                )
                .await?;
            Ok(ds
                .iter()
                .next()
                .map(|r| get_i64(r, ds.schema.as_ref(), "id"))
                .unwrap_or(0))
        } else {
            execute_sql_with_params(
                &self.db_id,
                None,
                "UPDATE cmx_plugin_trigger_binding SET kind=$2, trigger_key=$3, plugin_id=$4, \
                 function_name=$5, tenant_id=$6, enabled=$7, filter_expr=$8, payload_json=$9, updated_at=$10 \
                 WHERE id=$1",
                SqlParams::DataValues(vec![
                    DataValue::Int(b.id),
                    DataValue::String(kind_str(b.kind).into()),
                    DataValue::String(b.trigger_key.clone()),
                    DataValue::String(b.plugin_id.clone()),
                    DataValue::String(b.function_name.clone()),
                    opt_str(&b.tenant_id),
                    DataValue::Bool(b.enabled),
                    opt_str(&b.filter_expr),
                    payload,
                    DataValue::DateTime(now),
                ]),
            )
            .await
            .map_err(|e| format!("更新触发绑定失败: {e}"))?;
            Ok(b.id)
        }
    }

    async fn delete(&self, id: i64) -> Result<u64, String> {
        execute_sql_with_params(
            &self.db_id,
            None,
            "DELETE FROM cmx_plugin_trigger_binding WHERE id = $1",
            SqlParams::DataValues(vec![DataValue::Int(id)]),
        )
        .await
        .map_err(|e| format!("删除触发绑定失败: {e}"))
    }
}

// ————————————————————————— 助手 —————————————————————————

fn kind_str(k: TriggerKind) -> &'static str {
    match k {
        TriggerKind::Event => "event",
        TriggerKind::Cron => "cron",
        TriggerKind::BizHook => "bizhook",
    }
}

fn parse_kind(s: &str) -> TriggerKind {
    match s {
        "cron" => TriggerKind::Cron,
        "bizhook" => TriggerKind::BizHook,
        _ => TriggerKind::Event,
    }
}

fn rows_to_bindings(ds: &DataSet) -> Vec<TriggerBinding> {
    let schema = ds.schema.as_ref();
    let mut out = Vec::new();
    for r in ds.iter() {
        out.push(TriggerBinding {
            id: get_i64(r, schema, "id"),
            kind: parse_kind(&get_string(r, schema, "kind")),
            trigger_key: get_string(r, schema, "trigger_key"),
            plugin_id: get_string(r, schema, "plugin_id"),
            function_name: get_string(r, schema, "function_name"),
            tenant_id: get_opt_string(r, schema, "tenant_id"),
            enabled: get_bool(r, schema, "enabled"),
            filter_expr: get_opt_string(r, schema, "filter_expr"),
            payload_json: get_opt_json(r, schema, "payload_json"),
        });
    }
    out
}

fn opt_str(v: &Option<String>) -> DataValue {
    match v {
        Some(s) => DataValue::String(s.clone()),
        None => DataValue::Null,
    }
}

fn get_string(row: &Row, schema: &Schema, col: &str) -> String {
    match row.get_by_name(schema, col) {
        Some(DataValue::String(s)) => s.clone(),
        Some(DataValue::ShortStr(s)) | Some(DataValue::LongStr(s)) => s.to_string(),
        _ => String::new(),
    }
}

fn get_opt_string(row: &Row, schema: &Schema, col: &str) -> Option<String> {
    match row.get_by_name(schema, col) {
        Some(DataValue::String(s)) => Some(s.clone()),
        Some(DataValue::ShortStr(s)) | Some(DataValue::LongStr(s)) => Some(s.to_string()),
        _ => None,
    }
}

fn get_bool(row: &Row, schema: &Schema, col: &str) -> bool {
    matches!(row.get_by_name(schema, col), Some(DataValue::Bool(true)))
}

fn get_i64(row: &Row, schema: &Schema, col: &str) -> i64 {
    match row.get_by_name(schema, col) {
        Some(DataValue::Int(v)) => *v,
        _ => 0,
    }
}

fn get_opt_json(row: &Row, schema: &Schema, col: &str) -> Option<Value> {
    match row.get_by_name(schema, col) {
        Some(DataValue::Json(s)) => serde_json::from_str(s).ok(),
        Some(DataValue::String(s)) => serde_json::from_str(s).ok(),
        _ => None,
    }
}

#[cfg(test)]
mod it {
    //! 真机集成（需本机 PG + fico）。`CMX_IT_PG=1 cargo test -p cmx-plugin-trigger-store-pg -- --ignored --nocapture`
    use super::*;
    use cmx_database::get_default_db_manager;
    use cmx_database::{DbConfig, DbType};
    use cmx_plugin_trigger::TriggerBinding;

    async fn setup() -> String {
        let db_id = "cmx_it_trg".to_string();
        let cfg = DbConfig {
            db_type: DbType::Postgres,
            db_url: std::env::var("CMX_IT_PG_URL")
                .unwrap_or_else(|_| "postgres://postgres:postgres@127.0.0.1:5432/fico".into()),
            db_id: db_id.clone(),
            db_name: Some("it".into()),
            db_schema: Some("public".into()),
            default: true,
            pool_config: Default::default(),
            health_check_interval: 60,
            health_check_timeout: 5,
            domain_code: None,
            application_code: None,
            module_code: None,
            source_type: Some("default".into()),
        };
        get_default_db_manager().register_data_source(cfg).await.unwrap();
        db_id
    }

    #[tokio::test]
    #[ignore]
    async fn binding_crud_and_lookup() {
        if std::env::var("CMX_IT_PG").is_err() {
            eprintln!("跳过：设 CMX_IT_PG=1 启用");
            return;
        }
        let store = PgTriggerBindingStore::new(setup().await);
        store.ensure_schema().await.unwrap();

        let topic = format!("it.topic.{}", chrono::Utc::now().timestamp_micros());
        let id = store
            .save(&TriggerBinding::event(topic.clone(), "p-it", "on_it"))
            .await
            .unwrap();
        assert!(id > 0, "RETURNING id 应 > 0");

        // bindings_for 命中（tenant=None 宽松）。
        let hit = store
            .bindings_for(TriggerKind::Event, &topic, None)
            .await
            .unwrap();
        assert_eq!(hit.len(), 1);
        assert_eq!(hit[0].plugin_id, "p-it");
        assert!(hit[0].enabled);

        // delete。
        let n = store.delete(id).await.unwrap();
        assert_eq!(n, 1);
        let gone = store.bindings_for(TriggerKind::Event, &topic, None).await.unwrap();
        assert!(gone.is_empty());
        eprintln!("✅ trigger_binding CRUD + lookup roundtrip 通过（真机 PG）");
    }
}
