-- cr_report_sheet 允许「一报表 + 一版本」承载多个 sheet。
--
-- 背景：cr_report_sheet 早期定义遗留了一条 2 列唯一索引
--   uk_cr_report_sheet_1 UNIQUE (report_code, version_code)
-- 它把「同一报表同一版本只能有 1 个 sheet」写死。插入第 2 个 sheet 时必然报
--   duplicate key value violates unique constraint "uk_cr_report_sheet_1"
-- 表现为报表设计器「插入多 sheet 保存出错」。
--
-- 主键 PRIMARY KEY (report_code, version_code, sheet_index) 本就保证了 sheet 唯一性，
-- 且定义源 cmxfico_report_dct_meta_v1.json 的 uniqueKeys 已是 3 列
--   [["report_code","version_code","sheet_index"]]，
-- 故这条 2 列索引是过时孤儿，删除即可，DDL 同步不会再生成它。
DROP INDEX IF EXISTS uk_cr_report_sheet_1;
