[package]
name = "cmx-plugin-sdk"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# Extism PDK
extism-pdk = "1.4.1"
# 内部依赖 - 核心库
cmx-core = { workspace = true }
# 序列化框架
serde = { workspace = true, features = ["derive"] }
# JSON 序列化/反序列化
serde_json = { workspace = true }
# MessagePack 序列化/反序列化
rmp-serde = { workspace = true }
# 错误处理
thiserror = { workspace = true }
