-- ============================================================
-- CMX 业务库手工种子：总账字典（cf_* 36 表，华信集团 client=100 示例）
-- 前置条件：cf_* 表 DDL 由模型中心/插件运行时部署，建表完成后方可执行
-- 幂等：全部 INSERT 已加 ON CONFLICT DO NOTHING（任意唯一约束命中即跳过）
-- 来源：docs/sql/seed/cmxfico_dct_seed_data.sql 幂等化
-- ============================================================

INSERT INTO cf_dc_indicator (code, name, sort_no, status, is_system) VALUES ('S', '借方', 1, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_dc_indicator (code, name, sort_no, status, is_system) VALUES ('H', '贷方', 2, 1, 1) ON CONFLICT DO NOTHING;

-- 账户类型（account_type）  6 行
INSERT INTO cf_account_type (code, name, sort_no, status, is_system) VALUES ('A', '资产类', 1, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_account_type (code, name, sort_no, status, is_system) VALUES ('D', '负债类', 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_account_type (code, name, sort_no, status, is_system) VALUES ('K', '权益类', 3, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_account_type (code, name, sort_no, status, is_system) VALUES ('S', '收入/收益类', 4, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_account_type (code, name, sort_no, status, is_system) VALUES ('P', '支出/费用类', 5, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_account_type (code, name, sort_no, status, is_system) VALUES ('M', '物料类', 6, 1, 1) ON CONFLICT DO NOTHING;

-- 汇率类型（fx_rate_type）  4 行
INSERT INTO cf_fx_rate_type (code, name, sort_no, status, is_system) VALUES ('M', '平均汇率(月末)', 1, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_fx_rate_type (code, name, sort_no, status, is_system) VALUES ('B', '银行买入价', 2, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_fx_rate_type (code, name, sort_no, status, is_system) VALUES ('G', '银行卖出价', 3, 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_fx_rate_type (code, name, sort_no, status, is_system) VALUES ('AVG', '期间平均汇率', 4, 1, 1) ON CONFLICT DO NOTHING;

-- 货币（currency）  5 行
INSERT INTO cf_currency (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, symbol, decimals) VALUES ('CNY', '人民币', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, '¥', 2) ON CONFLICT DO NOTHING;
INSERT INTO cf_currency (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, symbol, decimals) VALUES ('USD', '美元', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, '$', 2) ON CONFLICT DO NOTHING;
INSERT INTO cf_currency (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, symbol, decimals) VALUES ('EUR', '欧元', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, '€', 2) ON CONFLICT DO NOTHING;
INSERT INTO cf_currency (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, symbol, decimals) VALUES ('HKD', '港元', 4, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'HK$', 2) ON CONFLICT DO NOTHING;
INSERT INTO cf_currency (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, symbol, decimals) VALUES ('JPY', '日元', 5, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, '¥', 0) ON CONFLICT DO NOTHING;

-- 国家（country）  5 行
INSERT INTO cf_country (code, name, sort_no, status, is_system, currency_code, iso_code_2, iso_code_3) VALUES ('CN', '中国', 1, 1, 1, 'CNY', 'CN', 'CHN') ON CONFLICT DO NOTHING;
INSERT INTO cf_country (code, name, sort_no, status, is_system, currency_code, iso_code_2, iso_code_3) VALUES ('US', '美国', 2, 1, 1, 'USD', 'US', 'USA') ON CONFLICT DO NOTHING;
INSERT INTO cf_country (code, name, sort_no, status, is_system, currency_code, iso_code_2, iso_code_3) VALUES ('DE', '德国', 3, 1, 1, 'EUR', 'DE', 'DEU') ON CONFLICT DO NOTHING;
INSERT INTO cf_country (code, name, sort_no, status, is_system, currency_code, iso_code_2, iso_code_3) VALUES ('HK', '中国香港', 4, 1, 1, 'HKD', 'HK', 'HKG') ON CONFLICT DO NOTHING;
INSERT INTO cf_country (code, name, sort_no, status, is_system, currency_code, iso_code_2, iso_code_3) VALUES ('JP', '日本', 5, 1, 1, 'JPY', 'JP', 'JPN') ON CONFLICT DO NOTHING;

-- 会计原则（acct_princ）  3 行
INSERT INTO cf_acct_princ (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, gaap_type, country_code) VALUES ('CNAS', '中国企业会计准则', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'LOCAL', 'CN') ON CONFLICT DO NOTHING;
INSERT INTO cf_acct_princ (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, gaap_type, country_code) VALUES ('IFRS', '国际财务报告准则', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'IFRS', NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_acct_princ (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, gaap_type, country_code) VALUES ('CAS', '中国会计准则(新)', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'LOCAL', 'CN') ON CONFLICT DO NOTHING;

-- 会计年度变式（fy_variant）  2 行
INSERT INTO cf_fy_variant (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, posting_periods, special_periods) VALUES ('K4', 'K4-会计年度变式(12正常+4特别)', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 12, 4) ON CONFLICT DO NOTHING;
INSERT INTO cf_fy_variant (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, posting_periods, special_periods) VALUES ('V9', 'V9-日历年度(12正常)', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 12, 0) ON CONFLICT DO NOTHING;

-- 字段状态组（fld_stat_grp）  4 行
INSERT INTO cf_fld_stat_grp (code, name, sort_no, status, is_system, field_status_variant, required_fields, optional_fields, suppressed_fields) VALUES ('G001', '一般字段状态组(基本)', 1, 1, 1, 'V001', 'account,profit_center', 'cost_center,text', '') ON CONFLICT DO NOTHING;
INSERT INTO cf_fld_stat_grp (code, name, sort_no, status, is_system, field_status_variant, required_fields, optional_fields, suppressed_fields) VALUES ('G002', '供应商字段状态组', 2, 1, 1, 'V002', 'account,vendor,baseline_date', 'payment_terms,text', '') ON CONFLICT DO NOTHING;
INSERT INTO cf_fld_stat_grp (code, name, sort_no, status, is_system, field_status_variant, required_fields, optional_fields, suppressed_fields) VALUES ('G003', '客户字段状态组', 3, 1, 1, 'V003', 'account,customer', 'payment_terms,text', '') ON CONFLICT DO NOTHING;
INSERT INTO cf_fld_stat_grp (code, name, sort_no, status, is_system, field_status_variant, required_fields, optional_fields, suppressed_fields) VALUES ('G004', '物料字段状态组', 4, 1, 1, 'V004', 'account,material', 'plant,text', '') ON CONFLICT DO NOTHING;

-- 凭证号码范围（number_range）  3 行
INSERT INTO cf_number_range (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, range_from, range_to, external_numbering) VALUES ('01', '总账凭证号范围', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, '0100000000', '0199999999', '0') ON CONFLICT DO NOTHING;
INSERT INTO cf_number_range (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, range_from, range_to, external_numbering) VALUES ('02', '供应商凭证号范围', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, '0200000000', '0299999999', '0') ON CONFLICT DO NOTHING;
INSERT INTO cf_number_range (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, range_from, range_to, external_numbering) VALUES ('03', '客户凭证号范围', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, '0300000000', '0399999999', '0') ON CONFLICT DO NOTHING;

-- 科目组（acct_group）  7 行
INSERT INTO cf_acct_group (code, name, sort_no, status, is_system, from_account, to_account) VALUES ('A001', '流动资产科目组', 1, 1, 1, '1001', '1299') ON CONFLICT DO NOTHING;
INSERT INTO cf_acct_group (code, name, sort_no, status, is_system, from_account, to_account) VALUES ('A002', '非流动资产科目组', 2, 1, 1, '1301', '1799') ON CONFLICT DO NOTHING;
INSERT INTO cf_acct_group (code, name, sort_no, status, is_system, from_account, to_account) VALUES ('L001', '流动负债科目组', 3, 1, 1, '2001', '2299') ON CONFLICT DO NOTHING;
INSERT INTO cf_acct_group (code, name, sort_no, status, is_system, from_account, to_account) VALUES ('L002', '非流动负债科目组', 4, 1, 1, '2501', '2799') ON CONFLICT DO NOTHING;
INSERT INTO cf_acct_group (code, name, sort_no, status, is_system, from_account, to_account) VALUES ('E001', '权益科目组', 5, 1, 1, '3001', '3299') ON CONFLICT DO NOTHING;
INSERT INTO cf_acct_group (code, name, sort_no, status, is_system, from_account, to_account) VALUES ('P001', '损益(收入)科目组', 6, 1, 1, '4001', '4999') ON CONFLICT DO NOTHING;
INSERT INTO cf_acct_group (code, name, sort_no, status, is_system, from_account, to_account) VALUES ('P002', '损益(成本费用)科目组', 7, 1, 1, '5001', '6999') ON CONFLICT DO NOTHING;

-- ====== 2. 客户端与组织架构 ======

-- 客户端（client）  2 行
INSERT INTO cf_client (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, logical_system, system_id, client_role) VALUES ('100', '华信集团(生产客户端)', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'CMX100', 'CMX', 'PRODUCTIVE') ON CONFLICT DO NOTHING;
INSERT INTO cf_client (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, logical_system, system_id, client_role) VALUES ('800', '华信集团(测试客户端)', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'CMX800', 'CMX', 'TEST') ON CONFLICT DO NOTHING;

-- 会计科目表（coa）  2 行
INSERT INTO cf_coa (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, coa_type) VALUES (1, '1000', '华信运营科目表', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'OPERATING') ON CONFLICT DO NOTHING;
INSERT INTO cf_coa (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, coa_type) VALUES (2, '2000', '华信合并科目表', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'GROUP') ON CONFLICT DO NOTHING;

-- 成本控制范围（ctrl_area）  1 行
INSERT INTO cf_ctrl_area (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, currency_code, coa_id, fy_variant_code) VALUES (1, '1000', '华信成本控制范围', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'CNY', 1, 'K4') ON CONFLICT DO NOTHING;

-- 公司(合并主体)（company）  1 行
INSERT INTO cf_company (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, country_code, currency_code, trading_partner_id, cons_method) VALUES (1, '1000', '华信集团有限公司(合并主体)', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 'CN', 'CNY', NULL, 'FULL') ON CONFLICT DO NOTHING;

-- 公司代码(核算主体)（comp_unit）  2 行
INSERT INTO cf_comp_unit (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, company_id, country_code, currency_code, coa_id, ctrl_area_id, vat_reg_no, fy_variant_code, credit_control_area) VALUES (1, '1000', '华信科技(北京)有限公司', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'CN', 'CNY', 1, 1000, '91110000MA01ABCD1X', 'K4', '1000') ON CONFLICT DO NOTHING;
INSERT INTO cf_comp_unit (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, company_id, country_code, currency_code, coa_id, ctrl_area_id, vat_reg_no, fy_variant_code, credit_control_area) VALUES (2, '2000', '华信制造(苏州)有限公司', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2021-06-01', NULL, NULL, NULL, 1000, 'CN', 'CNY', 1, 1000, '91320500MA02EFGH2Y', 'K4', '1000') ON CONFLICT DO NOTHING;

-- 业务范围（bus_area）  2 行
INSERT INTO cf_bus_area (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, comp_unit_id) VALUES (1, '1000', '主营业务范围', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 1000) ON CONFLICT DO NOTHING;
INSERT INTO cf_bus_area (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, comp_unit_id) VALUES (2, '2000', '其他业务范围', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 2000) ON CONFLICT DO NOTHING;

-- 功能范围（func_area）  4 行
INSERT INTO cf_func_area (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, function_category) VALUES (1, '1000', '管理职能', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO cf_func_area (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, function_category) VALUES (2, '2000', '销售职能', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'SALES') ON CONFLICT DO NOTHING;
INSERT INTO cf_func_area (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, function_category) VALUES (3, '3000', '生产职能', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'PROD') ON CONFLICT DO NOTHING;
INSERT INTO cf_func_area (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, function_category) VALUES (4, '4000', '研发职能', 4, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'R&D') ON CONFLICT DO NOTHING;

-- 段（segment）  2 行
INSERT INTO cf_segment (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, responsible_profit_center_id) VALUES (1, '1000', '科技业务分部', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_segment (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, responsible_profit_center_id) VALUES (2, '2000', '制造业务分部', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;

-- 利润中心（profit_ctr）  3 行
INSERT INTO cf_profit_ctr (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, segment_id, manager, ctrl_area_id, comp_unit_id, standard_hierarchy) VALUES (1, '1000', '总部利润中心', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, '张明', 1000, 1000, 'PRCTR-HQ') ON CONFLICT DO NOTHING;
INSERT INTO cf_profit_ctr (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, segment_id, manager, ctrl_area_id, comp_unit_id, standard_hierarchy) VALUES (2, '1100', '软件业务利润中心', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, '李华', 1000, 1000, 'PRCTR-SW') ON CONFLICT DO NOTHING;
INSERT INTO cf_profit_ctr (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, segment_id, manager, ctrl_area_id, comp_unit_id, standard_hierarchy) VALUES (3, '2000', '苏州工厂利润中心', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2021-06-01', NULL, NULL, NULL, 2000, '王强', 1000, 2000, 'PRCTR-SZ') ON CONFLICT DO NOTHING;

-- 回填 segment.responsible_profit_center_id（打破循环依赖后补全）
UPDATE cf_segment SET responsible_profit_center_id = 1100 WHERE code = '1000';
UPDATE cf_segment SET responsible_profit_center_id = 2000 WHERE code = '2000';

-- 成本中心（cost_center）  5 行
INSERT INTO cf_cost_center (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, profit_ctr_id, manager, ctrl_area_id, comp_unit_id, func_area_id, bus_area_id, cost_center_category) VALUES (1, '10001000', '总部-管理中心', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, '张明', 1000, 1000, 1000, 1000, 'W') ON CONFLICT DO NOTHING;
INSERT INTO cf_cost_center (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, profit_ctr_id, manager, ctrl_area_id, comp_unit_id, func_area_id, bus_area_id, cost_center_category) VALUES (2, '10001100', '总部-软件研发部', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1100, '李华', 1000, 1000, 4000, 1000, 'L') ON CONFLICT DO NOTHING;
INSERT INTO cf_cost_center (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, profit_ctr_id, manager, ctrl_area_id, comp_unit_id, func_area_id, bus_area_id, cost_center_category) VALUES (3, '10001200', '总部-销售部', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1100, '赵敏', 1000, 1000, 2000, 1000, 'H') ON CONFLICT DO NOTHING;
INSERT INTO cf_cost_center (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, profit_ctr_id, manager, ctrl_area_id, comp_unit_id, func_area_id, bus_area_id, cost_center_category) VALUES (4, '20001000', '苏州-生产车间', 4, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2021-06-01', NULL, NULL, NULL, 2000, '王强', 1000, 2000, 3000, 2000, 'F') ON CONFLICT DO NOTHING;
INSERT INTO cf_cost_center (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, profit_ctr_id, manager, ctrl_area_id, comp_unit_id, func_area_id, bus_area_id, cost_center_category) VALUES (5, '20002000', '苏州-品控部', 5, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2021-06-01', NULL, NULL, NULL, 2000, '陈刚', 1000, 2000, 3000, 2000, 'L') ON CONFLICT DO NOTHING;

-- ====== 3. 总账科目体系（自分级，物化路径 . 分隔） ======

-- 总账科目（gl_account）  29 行
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (1, '1', '资产类', 10, 1, NULL, '1', 1, 0, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'A001', 'A', 'BS', NULL, 'CNY', 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (2, '2', '负债类', 20, 1, NULL, '2', 1, 0, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'L001', 'D', 'BS', NULL, 'CNY', 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (3, '3', '权益类', 30, 1, NULL, '3', 1, 0, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'E001', 'K', 'BS', NULL, 'CNY', 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (4, '4', '收入类', 40, 1, NULL, '4', 1, 0, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'P001', 'S', 'PL', NULL, 'CNY', 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (5, '5', '成本费用类', 50, 1, NULL, '5', 1, 0, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'P002', 'P', 'PL', NULL, 'CNY', 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (1001, '1001', '库存现金', 101, 1, 1, '1.1001', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'A001', 'A', 'BS', 0, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (1002, '1002', '银行存款', 102, 1, 1, '1.1002', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'A001', 'A', 'BS', 0, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (1122, '1122', '应收账款', 103, 1, 1, '1.1122', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'A001', 'A', 'BS', 1, 'CNY', 1000, 'G003', 'D', 'V', 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (1123, '1123', '预付账款', 104, 1, 1, '1.1123', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'A001', 'A', 'BS', 1, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (1221, '1221', '其他应收款', 105, 1, 1, '1.1221', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'A001', 'A', 'BS', 1, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (1601, '1601', '固定资产', 106, 1, 1, '1.1601', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'A002', 'A', 'BS', 0, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (1602, '1602', '累计折旧', 107, 1, 1, '1.1602', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'A002', 'A', 'BS', 0, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (2001, '2001', '短期借款', 201, 1, 2, '2.2001', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'L001', 'D', 'BS', 1, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (2202, '2202', '应付账款', 202, 1, 2, '2.2202', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'L001', 'D', 'BS', 1, 'CNY', 1000, 'G002', 'K', 'V', 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (2203, '2203', '预收账款', 203, 1, 2, '2.2203', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'L001', 'D', 'BS', 1, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (2211, '2211', '应付职工薪酬', 204, 1, 2, '2.2211', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'L001', 'D', 'BS', 0, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (2221, '2221', '应交税费', 205, 1, 2, '2.2221', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'L001', 'D', 'BS', 0, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (222101, '222101', '应交增值税-进项税额', 2051, 1, 2221, '2.2221.222101', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'L001', 'D', 'BS', 0, 'CNY', 1000, NULL, NULL, NULL, 1, '014', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (222102, '222102', '应交增值税-销项税额', 2052, 1, 2221, '2.2221.222102', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'L001', 'D', 'BS', 0, 'CNY', 1000, NULL, NULL, NULL, 1, '014', NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (3001, '3001', '实收资本', 301, 1, 3, '3.3001', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'E001', 'K', 'BS', 0, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (3002, '3002', '资本公积', 302, 1, 3, '3.3002', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'E001', 'K', 'BS', 0, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (3103, '3103', '本年利润', 303, 1, 3, '3.3103', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'E001', 'K', 'BS', 0, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (4101, '4101', '主营业务收入', 401, 1, 4, '4.4101', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'P001', 'S', 'PL', 0, 'CNY', 1000, NULL, NULL, 'V', 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (4102, '4102', '其他业务收入', 402, 1, 4, '4.4102', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'P001', 'S', 'PL', 0, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (5301, '5301', '主营业务成本', 501, 1, 5, '5.5301', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'P002', 'P', 'PL', 0, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (5601, '5601', '销售费用', 502, 1, 5, '5.5601', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'P002', 'P', 'PL', 0, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (5602, '5602', '管理费用', 503, 1, 5, '5.5602', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'P002', 'P', 'PL', 0, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (5603, '5603', '研发费用', 504, 1, 5, '5.5603', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'P002', 'P', 'PL', 0, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_gl_account (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, coa_id, acct_group_code, account_type_code, pl_bs_flag, open_item_mgmt, account_currency_code, comp_unit_id, fld_stat_grp_code, reconciliation_account_type_code, tax_category, line_item_display, sort_key, post_automatically_only, planning_level) VALUES (6711, '6711', '营业外支出', 505, 1, 5, '5.6711', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 1000, 'P002', 'P', 'PL', 0, 'CNY', 1000, NULL, NULL, NULL, 1, NULL, NULL, NULL) ON CONFLICT DO NOTHING;

-- 财务报表版本（fs_version）  6 行
INSERT INTO cf_fs_version (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fs_item_type) VALUES (1000000, '1000000', '资产负债表', 1, 1, NULL, '1000000', 1, 0, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 'HEADER') ON CONFLICT DO NOTHING;
INSERT INTO cf_fs_version (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fs_item_type) VALUES (1100000, '1100000', '流动资产', 11, 1, 1000000, '1000000.1100000', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 'NODE') ON CONFLICT DO NOTHING;
INSERT INTO cf_fs_version (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fs_item_type) VALUES (1200000, '1200000', '非流动资产', 12, 1, 1000000, '1000000.1200000', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 'NODE') ON CONFLICT DO NOTHING;
INSERT INTO cf_fs_version (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fs_item_type) VALUES (2000000, '2000000', '利润表', 2, 1, NULL, '2000000', 1, 0, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 'HEADER') ON CONFLICT DO NOTHING;
INSERT INTO cf_fs_version (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fs_item_type) VALUES (2100000, '2100000', '营业收入', 21, 1, 2000000, '2000000.2100000', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 'NODE') ON CONFLICT DO NOTHING;
INSERT INTO cf_fs_version (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fs_item_type) VALUES (2200000, '2200000', '营业成本费用', 22, 1, 2000000, '2000000.2200000', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 'NODE') ON CONFLICT DO NOTHING;

-- ====== 4. 凭证控制（类型/记账码/号码/特别总账） ======

-- 凭证类型（doc_type）  6 行
INSERT INTO cf_doc_type (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, number_range_code, reverse_doc_type_code, allowed_account_types, negative_posting_allowed, cross_company_allowed) VALUES ('SA', '总账凭证(G/L)', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, '01', 'AB', 'AS', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO cf_doc_type (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, number_range_code, reverse_doc_type_code, allowed_account_types, negative_posting_allowed, cross_company_allowed) VALUES ('KR', '供应商发票(应付)', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, '02', 'AB', 'K', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO cf_doc_type (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, number_range_code, reverse_doc_type_code, allowed_account_types, negative_posting_allowed, cross_company_allowed) VALUES ('DR', '客户发票(应收)', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, '03', 'AB', 'D', 0, 0) ON CONFLICT DO NOTHING;
INSERT INTO cf_doc_type (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, number_range_code, reverse_doc_type_code, allowed_account_types, negative_posting_allowed, cross_company_allowed) VALUES ('AB', '会计调整/冲销', 4, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, '01', 'AB', 'ASDK', 1, 0) ON CONFLICT DO NOTHING;
INSERT INTO cf_doc_type (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, number_range_code, reverse_doc_type_code, allowed_account_types, negative_posting_allowed, cross_company_allowed) VALUES ('KZ', '付款(银行付款)', 5, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, '02', 'AB', 'K', 1, 0) ON CONFLICT DO NOTHING;
INSERT INTO cf_doc_type (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, number_range_code, reverse_doc_type_code, allowed_account_types, negative_posting_allowed, cross_company_allowed) VALUES ('DZ', '收款(银行收款)', 6, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, '03', 'AB', 'D', 1, 0) ON CONFLICT DO NOTHING;

-- 记账码（posting_key）  6 行
INSERT INTO cf_posting_key (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, debit_credit_code, account_type_code, fld_stat_grp_code, special_gl_allowed) VALUES ('40', '借方-总账科目', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'S', 'S', 'G001', 0) ON CONFLICT DO NOTHING;
INSERT INTO cf_posting_key (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, debit_credit_code, account_type_code, fld_stat_grp_code, special_gl_allowed) VALUES ('50', '贷方-总账科目', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'H', 'S', 'G001', 0) ON CONFLICT DO NOTHING;
INSERT INTO cf_posting_key (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, debit_credit_code, account_type_code, fld_stat_grp_code, special_gl_allowed) VALUES ('01', '借方-客户', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'S', 'D', 'G003', 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_posting_key (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, debit_credit_code, account_type_code, fld_stat_grp_code, special_gl_allowed) VALUES ('11', '贷方-客户', 4, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'H', 'D', 'G003', 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_posting_key (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, debit_credit_code, account_type_code, fld_stat_grp_code, special_gl_allowed) VALUES ('21', '贷方-供应商', 5, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'H', 'K', 'G002', 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_posting_key (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, debit_credit_code, account_type_code, fld_stat_grp_code, special_gl_allowed) VALUES ('31', '借方-供应商', 6, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'S', 'K', 'G002', 1) ON CONFLICT DO NOTHING;

-- 特别总账标识（spl_gl_ind）  3 行
INSERT INTO cf_spl_gl_ind (code, name, sort_no, status, is_system, special_gl_type, account_type_code, reconciliation_account_id, special_gl_account_id) VALUES ('A', '预付账款(特别总账)', 1, 1, 1, 'DOWN_PAYMENT', 'K', 2202, 1123) ON CONFLICT DO NOTHING;
INSERT INTO cf_spl_gl_ind (code, name, sort_no, status, is_system, special_gl_type, account_type_code, reconciliation_account_id, special_gl_account_id) VALUES ('F', '预收账款(特别总账)', 2, 1, 1, 'DOWN_PAYMENT', 'D', 1122, 2203) ON CONFLICT DO NOTHING;
INSERT INTO cf_spl_gl_ind (code, name, sort_no, status, is_system, special_gl_type, account_type_code, reconciliation_account_id, special_gl_account_id) VALUES ('W', '应收票据(特别总账)', 3, 1, 1, 'BILL', 'D', 1122, 1121) ON CONFLICT DO NOTHING;

-- ====== 5. 税、付款、期间、分类账 ======

-- 税码（tax_code）  6 行
INSERT INTO cf_tax_code (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, tax_type, tax_rate, target_tax_account_id, input_output, country_code) VALUES ('J0', '进项税-0%进项', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'VAT', 0.0, 222101, 'V', 'CN') ON CONFLICT DO NOTHING;
INSERT INTO cf_tax_code (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, tax_type, tax_rate, target_tax_account_id, input_output, country_code) VALUES ('J1', '进项税-3%进项', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'VAT', 3.0, 222101, 'V', 'CN') ON CONFLICT DO NOTHING;
INSERT INTO cf_tax_code (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, tax_type, tax_rate, target_tax_account_id, input_output, country_code) VALUES ('J6', '进项税-13%进项', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'VAT', 13.0, 222101, 'V', 'CN') ON CONFLICT DO NOTHING;
INSERT INTO cf_tax_code (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, tax_type, tax_rate, target_tax_account_id, input_output, country_code) VALUES ('X0', '销项税-0%销项', 4, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'VAT', 0.0, 222102, 'V', 'CN') ON CONFLICT DO NOTHING;
INSERT INTO cf_tax_code (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, tax_type, tax_rate, target_tax_account_id, input_output, country_code) VALUES ('X1', '销项税-1%销项', 5, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'VAT', 1.0, 222102, 'V', 'CN') ON CONFLICT DO NOTHING;
INSERT INTO cf_tax_code (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, tax_type, tax_rate, target_tax_account_id, input_output, country_code) VALUES ('X6', '销项税-13%销项', 6, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 'VAT', 13.0, 222102, 'V', 'CN') ON CONFLICT DO NOTHING;

-- 付款条件（pay_terms）  4 行
INSERT INTO cf_pay_terms (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, net_due_days, discount_pct_1, discount_days_1, discount_days_2, discount_pct_2, baseline_date_rule) VALUES ('0001', '立即付款(0天)', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 0, 0.0, '0', '0', 0.0, 'DOC') ON CONFLICT DO NOTHING;
INSERT INTO cf_pay_terms (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, net_due_days, discount_pct_1, discount_days_1, discount_days_2, discount_pct_2, baseline_date_rule) VALUES ('0014', '14天净额', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 14, 0.0, '0', '0', 0.0, 'DOC') ON CONFLICT DO NOTHING;
INSERT INTO cf_pay_terms (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, net_due_days, discount_pct_1, discount_days_1, discount_days_2, discount_pct_2, baseline_date_rule) VALUES ('0030', '30天净额(2/10)', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 30, 2.0, '10', '20', 1.0, 'DOC') ON CONFLICT DO NOTHING;
INSERT INTO cf_pay_terms (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, net_due_days, discount_pct_1, discount_days_1, discount_days_2, discount_pct_2, baseline_date_rule) VALUES ('0060', '60天净额', 4, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 60, 0.0, '0', '0', 0.0, 'DOC') ON CONFLICT DO NOTHING;

-- 付款方式（pay_method）  3 行
INSERT INTO cf_pay_method (code, name, sort_no, status, is_system, payment_type, country_code, bank_transfer, check_payment) VALUES ('T', '银行转账', 1, 1, 1, 'BANK_TRANSFER', 'CN', 1, 0) ON CONFLICT DO NOTHING;
INSERT INTO cf_pay_method (code, name, sort_no, status, is_system, payment_type, country_code, bank_transfer, check_payment) VALUES ('C', '支票付款', 2, 1, 1, 'CHECK', 'CN', 0, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_pay_method (code, name, sort_no, status, is_system, payment_type, country_code, bank_transfer, check_payment) VALUES ('D', '银行汇票', 3, 1, 1, 'DRAFT', 'CN', 0, 0) ON CONFLICT DO NOTHING;

-- 分类账（ledger）  2 行
INSERT INTO cf_ledger (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, leading_ledger, acct_princ_code, ledger_type, extension_ledger_code, currency_code, comp_unit_id) VALUES ('0L', '主分类账(记账本位币)', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 1, 'CNAS', 'LEADING', NULL, 'CNY', 1000) ON CONFLICT DO NOTHING;
INSERT INTO cf_ledger (code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, leading_ledger, acct_princ_code, ledger_type, extension_ledger_code, currency_code, comp_unit_id) VALUES ('CN', '集团合并分类账(集团货币)', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 1, 0, 'IFRS', 'NON_LEADING', NULL, 'CNY', 1000) ON CONFLICT DO NOTHING;

-- 会计期间（fisc_period）  16 行
INSERT INTO cf_fisc_period (code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fiscal_year, period_no, period_end_date, special_period, posting_allowed) VALUES ('2026-01', '2026年第1期', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-01-01', '2026-01-31', NULL, NULL, '2026', 1, '2026-01-31', 0, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_fisc_period (code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fiscal_year, period_no, period_end_date, special_period, posting_allowed) VALUES ('2026-02', '2026年第2期', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-02-01', '2026-02-28', NULL, NULL, '2026', 2, '2026-02-28', 0, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_fisc_period (code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fiscal_year, period_no, period_end_date, special_period, posting_allowed) VALUES ('2026-03', '2026年第3期', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-03-01', '2026-03-31', NULL, NULL, '2026', 3, '2026-03-31', 0, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_fisc_period (code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fiscal_year, period_no, period_end_date, special_period, posting_allowed) VALUES ('2026-04', '2026年第4期', 4, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-04-01', '2026-04-30', NULL, NULL, '2026', 4, '2026-04-30', 0, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_fisc_period (code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fiscal_year, period_no, period_end_date, special_period, posting_allowed) VALUES ('2026-05', '2026年第5期', 5, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-05-01', '2026-05-31', NULL, NULL, '2026', 5, '2026-05-31', 0, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_fisc_period (code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fiscal_year, period_no, period_end_date, special_period, posting_allowed) VALUES ('2026-06', '2026年第6期', 6, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-06-01', '2026-06-30', NULL, NULL, '2026', 6, '2026-06-30', 0, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_fisc_period (code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fiscal_year, period_no, period_end_date, special_period, posting_allowed) VALUES ('2026-07', '2026年第7期', 7, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-07-01', '2026-07-31', NULL, NULL, '2026', 7, '2026-07-31', 0, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_fisc_period (code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fiscal_year, period_no, period_end_date, special_period, posting_allowed) VALUES ('2026-08', '2026年第8期', 8, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-08-01', '2026-08-31', NULL, NULL, '2026', 8, '2026-08-31', 0, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_fisc_period (code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fiscal_year, period_no, period_end_date, special_period, posting_allowed) VALUES ('2026-09', '2026年第9期', 9, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-09-01', '2026-09-30', NULL, NULL, '2026', 9, '2026-09-30', 0, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_fisc_period (code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fiscal_year, period_no, period_end_date, special_period, posting_allowed) VALUES ('2026-10', '2026年第10期', 10, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-10-01', '2026-10-31', NULL, NULL, '2026', 10, '2026-10-31', 0, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_fisc_period (code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fiscal_year, period_no, period_end_date, special_period, posting_allowed) VALUES ('2026-11', '2026年第11期', 11, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-11-01', '2026-11-30', NULL, NULL, '2026', 11, '2026-11-30', 0, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_fisc_period (code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fiscal_year, period_no, period_end_date, special_period, posting_allowed) VALUES ('2026-12', '2026年第12期', 12, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-12-01', '2026-12-31', NULL, NULL, '2026', 12, '2026-12-31', 0, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_fisc_period (code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fiscal_year, period_no, period_end_date, special_period, posting_allowed) VALUES ('2026-13', '2026年第13期(特别期)', 13, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-12-31', '2026-12-31', NULL, NULL, '2026', 13, '2026-12-31', 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_fisc_period (code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fiscal_year, period_no, period_end_date, special_period, posting_allowed) VALUES ('2026-14', '2026年第14期(特别期)', 14, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-12-31', '2026-12-31', NULL, NULL, '2026', 14, '2026-12-31', 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_fisc_period (code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fiscal_year, period_no, period_end_date, special_period, posting_allowed) VALUES ('2026-15', '2026年第15期(特别期)', 15, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-12-31', '2026-12-31', NULL, NULL, '2026', 15, '2026-12-31', 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO cf_fisc_period (code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, fiscal_year, period_no, period_end_date, special_period, posting_allowed) VALUES ('2026-16', '2026年第16期(特别期)', 16, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-12-31', '2026-12-31', NULL, NULL, '2026', 16, '2026-12-31', 1, 1) ON CONFLICT DO NOTHING;

-- ====== 6. 业务伙伴、开户行、CO 对象（订单/WBS） ======

-- 业务伙伴(客户/供应商)（bus_partner）  5 行
INSERT INTO cf_bus_partner (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, bp_role, recon_account_id, country_code, pay_terms_code, comp_unit_id, customer_no, vendor_no, pay_method_code, partner_company_id) VALUES (1, 'C10001', '北京云创科技有限公司', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-03-01', NULL, NULL, NULL, 'CUSTOMER', 1122, 'CN', '0030', 1000, 'C10001', NULL, 'T', NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_bus_partner (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, bp_role, recon_account_id, country_code, pay_terms_code, comp_unit_id, customer_no, vendor_no, pay_method_code, partner_company_id) VALUES (2, 'C10002', '上海数联信息技术有限公司', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-05-15', NULL, NULL, NULL, 'CUSTOMER', 1122, 'CN', '0060', 1000, 'C10002', NULL, 'T', NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_bus_partner (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, bp_role, recon_account_id, country_code, pay_terms_code, comp_unit_id, customer_no, vendor_no, pay_method_code, partner_company_id) VALUES (3, 'V20001', '深圳市硬件供应链有限公司', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-02-01', NULL, NULL, NULL, 'VENDOR', 2202, 'CN', '0030', 1000, NULL, 'V20001', 'T', NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_bus_partner (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, bp_role, recon_account_id, country_code, pay_terms_code, comp_unit_id, customer_no, vendor_no, pay_method_code, partner_company_id) VALUES (4, 'V20002', '苏州明盛金属材料厂', 4, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2021-06-01', NULL, NULL, NULL, 'VENDOR', 2202, 'CN', '0014', 2000, NULL, 'V20002', 'T', NULL) ON CONFLICT DO NOTHING;
INSERT INTO cf_bus_partner (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, bp_role, recon_account_id, country_code, pay_terms_code, comp_unit_id, customer_no, vendor_no, pay_method_code, partner_company_id) VALUES (5, 'B30001', '华信集团财务公司(关联方)', 5, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 'BOTH', 1221, 'CN', '0001', 1000, 'B30001', 'B30001', 'T', 1000) ON CONFLICT DO NOTHING;

-- 开户行/银行（house_bank）  4 行
INSERT INTO cf_house_bank (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, bank_country_code, account_no, currency_code, gl_account_id, comp_unit_id, bank_key, house_bank_key, bank_account_id) VALUES (1, 'BK01', '工商银行北京中关村支行-基本户', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 'CN', '6222020100012345678', 'CNY', 1002, 1000, 'ICBC-010', 'BK01', '01') ON CONFLICT DO NOTHING;
INSERT INTO cf_house_bank (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, bank_country_code, account_no, currency_code, gl_account_id, comp_unit_id, bank_key, house_bank_key, bank_account_id) VALUES (2, 'BK02', '建设银行北京海淀支行-一般户', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 'CN', '6217000100023456789', 'CNY', 1002, 1000, 'CCB-010', 'BK02', '02') ON CONFLICT DO NOTHING;
INSERT INTO cf_house_bank (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, bank_country_code, account_no, currency_code, gl_account_id, comp_unit_id, bank_key, house_bank_key, bank_account_id) VALUES (3, 'BK03', '中国银行苏州工业园区支行', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2021-06-01', NULL, NULL, NULL, 'CN', '6217000500034567890', 'CNY', 1002, 2000, 'BOC-050', 'BK03', '01') ON CONFLICT DO NOTHING;
INSERT INTO cf_house_bank (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, bank_country_code, account_no, currency_code, gl_account_id, comp_unit_id, bank_key, house_bank_key, bank_account_id) VALUES (4, 'BK04', '花旗银行上海分行-美元户', 4, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-09-01', NULL, NULL, NULL, 'US', '36010012345678', 'USD', 1002, 1000, 'CITI-SHA', 'BK04', '01') ON CONFLICT DO NOTHING;

-- 内部订单（int_order）  3 行
INSERT INTO cf_int_order (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, order_type, responsible_cc_id, ctrl_area_id, comp_unit_id, profit_ctr_id) VALUES (1, '10000001', '2026年市场推广专项订单', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 0, 'MARKETING', 10001200, 1000, 1000, 1100) ON CONFLICT DO NOTHING;
INSERT INTO cf_int_order (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, order_type, responsible_cc_id, ctrl_area_id, comp_unit_id, profit_ctr_id) VALUES (2, '10000002', 'ERP实施资本化订单', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 0, 'CAPEX', 10001000, 1000, 1000, 1000) ON CONFLICT DO NOTHING;
INSERT INTO cf_int_order (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, is_system, order_type, responsible_cc_id, ctrl_area_id, comp_unit_id, profit_ctr_id) VALUES (3, '20000001', '苏州工厂设备大修订单', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, 0, 'MAINTENANCE', 20002000, 1000, 2000, 2000) ON CONFLICT DO NOTHING;

-- WBS元素(项目)（wbs_element）  3 行
INSERT INTO cf_wbs_element (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, responsible_cc_id, project_id, comp_unit_id, profit_ctr_id) VALUES (1, 'PRJ-2026-001', '2026新一代产品研发项目', 1, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-01-01', NULL, NULL, NULL, 10001100, 'PRJ-2026-001', 1000, 1100) ON CONFLICT DO NOTHING;
INSERT INTO cf_wbs_element (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, responsible_cc_id, project_id, comp_unit_id, profit_ctr_id) VALUES (2, 'PRJ-2026-001-01', '需求分析与设计', 2, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-01-01', NULL, NULL, NULL, 10001100, 'PRJ-2026-001', 1000, 1100) ON CONFLICT DO NOTHING;
INSERT INTO cf_wbs_element (id, code, name, sort_no, status, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, responsible_cc_id, project_id, comp_unit_id, profit_ctr_id) VALUES (3, 'PRJ-2026-001-02', '开发与测试', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2026-03-01', NULL, NULL, NULL, 10001100, 'PRJ-2026-001', 1000, 1100) ON CONFLICT DO NOTHING;

-- ====== 7. 合并组织机构（自分级：集团→分部→合并单元） ======

-- 合并组织机构（cons_org）  5 行
INSERT INTO cf_cons_org (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, org_type, comp_unit_id, cons_method, ownership_pct) VALUES (1000, '1000', '华信集团(合并集团)', 1, 1, NULL, '1000', 1, 0, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 'GROUP', NULL, 'FULL', 100.0) ON CONFLICT DO NOTHING;
INSERT INTO cf_cons_org (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, org_type, comp_unit_id, cons_method, ownership_pct) VALUES (100010, '1000-10', '科技业务分部', 2, 1, 1000, '1000.1000-10', 2, 0, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 'SEGMENT', 1, 'FULL', 100.0) ON CONFLICT DO NOTHING;
INSERT INTO cf_cons_org (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, org_type, comp_unit_id, cons_method, ownership_pct) VALUES (100020, '1000-20', '制造业务分部', 3, 1, 1000, '1000.1000-20', 2, 0, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 'SEGMENT', 2, 'FULL', 100.0) ON CONFLICT DO NOTHING;
INSERT INTO cf_cons_org (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, org_type, comp_unit_id, cons_method, ownership_pct) VALUES (10001001, '1000-10-01', '华信科技(北京)', 4, 1, 100010, '1000-10.1000-10-01', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 'UNIT', 1, 'FULL', 100.0) ON CONFLICT DO NOTHING;
INSERT INTO cf_cons_org (id, code, name, sort_no, status, parent_id, full_path, level_no, is_leaf, create_by, create_time, update_by, update_time, effective_from, effective_to, disabled_reason, disabled_time, org_type, comp_unit_id, cons_method, ownership_pct) VALUES (10002001, '1000-20-01', '华信制造(苏州)', 5, 1, 100020, '1000-20.1000-20-01', 3, 1, NULL, '2026-01-01 00:00:00', NULL, NULL, '2020-01-01', NULL, NULL, NULL, 'UNIT', 2, 'FULL', 100.0) ON CONFLICT DO NOTHING;

-- =================================================================
-- 字典表种子数据导入完成：共 35 张字典表
-- =================================================================
