-- =============================================
-- fico-db 报表「数据元素」种子数据 (DML) —— 由 gen_fico_cr_element_seed.py 生成，勿手改
--   cr_element_category 7 大类 · cr_data_element 若干元素
-- 数据元素 = 报表单元格取数的最小语义单位（对标科目/指标）。设计器左侧「数据元素」面板读此二表。
-- 幂等：按本脚本 code 精确清理再插入，可重复执行。
-- 依赖：cr_element_category / cr_data_element 已由报表数据字典元数据部署到 fico-db。
-- =============================================

-- 元素大类 cr_element_category
DELETE FROM cr_element_category WHERE code IN ('balance','income','cashflow','production','sales','cost','tax');
INSERT INTO cr_element_category (code,name,sort_no,status,remark,create_time) VALUES ('balance','资产负债类',1,1,NULL,CURRENT_TIMESTAMP);
INSERT INTO cr_element_category (code,name,sort_no,status,remark,create_time) VALUES ('income','损益类',2,1,NULL,CURRENT_TIMESTAMP);
INSERT INTO cr_element_category (code,name,sort_no,status,remark,create_time) VALUES ('cashflow','现金流量类',3,1,NULL,CURRENT_TIMESTAMP);
INSERT INTO cr_element_category (code,name,sort_no,status,remark,create_time) VALUES ('production','生产类',4,1,NULL,CURRENT_TIMESTAMP);
INSERT INTO cr_element_category (code,name,sort_no,status,remark,create_time) VALUES ('sales','销售类',5,1,NULL,CURRENT_TIMESTAMP);
INSERT INTO cr_element_category (code,name,sort_no,status,remark,create_time) VALUES ('cost','成本费用类',6,1,NULL,CURRENT_TIMESTAMP);
INSERT INTO cr_element_category (code,name,sort_no,status,remark,create_time) VALUES ('tax','税务类',7,1,NULL,CURRENT_TIMESTAMP);

-- 数据元素 cr_data_element（按大类分组，code = {前缀}_{NN}）
DELETE FROM cr_data_element WHERE code ~ '^(BS|PL|CF|PD|SL|CO|TX)_[0-9]{2}$';
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_01','货币资金','balance','amount','元',2,'gl','none',NULL,NULL,1,1,'资产负债类 · 货币资金',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_02','交易性金融资产','balance','amount','元',2,'gl','none',NULL,NULL,2,1,'资产负债类 · 交易性金融资产',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_03','应收票据','balance','amount','元',2,'gl','none',NULL,NULL,3,1,'资产负债类 · 应收票据',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_04','应收账款','balance','amount','元',2,'gl','none',NULL,NULL,4,1,'资产负债类 · 应收账款',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_05','预付款项','balance','amount','元',2,'gl','none',NULL,NULL,5,1,'资产负债类 · 预付款项',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_06','其他应收款','balance','amount','元',2,'gl','none',NULL,NULL,6,1,'资产负债类 · 其他应收款',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_07','存货','balance','amount','元',2,'gl','none',NULL,NULL,7,1,'资产负债类 · 存货',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_08','固定资产','balance','amount','元',2,'gl','none',NULL,NULL,8,1,'资产负债类 · 固定资产',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_09','在建工程','balance','amount','元',2,'gl','none',NULL,NULL,9,1,'资产负债类 · 在建工程',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_10','无形资产','balance','amount','元',2,'gl','none',NULL,NULL,10,1,'资产负债类 · 无形资产',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_11','资产总计','balance','amount','元',2,'calc','calc',NULL,NULL,11,1,'资产负债类 · 资产总计',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_12','短期借款','balance','amount','元',2,'gl','none',NULL,NULL,12,1,'资产负债类 · 短期借款',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_13','应付票据','balance','amount','元',2,'gl','none',NULL,NULL,13,1,'资产负债类 · 应付票据',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_14','应付账款','balance','amount','元',2,'gl','none',NULL,NULL,14,1,'资产负债类 · 应付账款',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_15','预收款项','balance','amount','元',2,'gl','none',NULL,NULL,15,1,'资产负债类 · 预收款项',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_16','应付职工薪酬','balance','amount','元',2,'gl','none',NULL,NULL,16,1,'资产负债类 · 应付职工薪酬',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_17','应交税费','balance','amount','元',2,'gl','none',NULL,NULL,17,1,'资产负债类 · 应交税费',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_18','长期借款','balance','amount','元',2,'gl','none',NULL,NULL,18,1,'资产负债类 · 长期借款',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_19','负债合计','balance','amount','元',2,'calc','calc',NULL,NULL,19,1,'资产负债类 · 负债合计',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_20','实收资本','balance','amount','元',2,'gl','none',NULL,NULL,20,1,'资产负债类 · 实收资本',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_21','资本公积','balance','amount','元',2,'gl','none',NULL,NULL,21,1,'资产负债类 · 资本公积',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_22','盈余公积','balance','amount','元',2,'gl','none',NULL,NULL,22,1,'资产负债类 · 盈余公积',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_23','未分配利润','balance','amount','元',2,'gl','none',NULL,NULL,23,1,'资产负债类 · 未分配利润',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('BS_24','所有者权益合计','balance','amount','元',2,'calc','calc',NULL,NULL,24,1,'资产负债类 · 所有者权益合计',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PL_01','营业收入','income','amount','元',2,'gl','none',NULL,NULL,25,1,'损益类 · 营业收入',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PL_02','营业成本','income','amount','元',2,'gl','none',NULL,NULL,26,1,'损益类 · 营业成本',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PL_03','税金及附加','income','amount','元',2,'gl','none',NULL,NULL,27,1,'损益类 · 税金及附加',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PL_04','销售费用','income','amount','元',2,'gl','none',NULL,NULL,28,1,'损益类 · 销售费用',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PL_05','管理费用','income','amount','元',2,'gl','none',NULL,NULL,29,1,'损益类 · 管理费用',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PL_06','研发费用','income','amount','元',2,'gl','none',NULL,NULL,30,1,'损益类 · 研发费用',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PL_07','财务费用','income','amount','元',2,'gl','none',NULL,NULL,31,1,'损益类 · 财务费用',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PL_08','投资收益','income','amount','元',2,'gl','none',NULL,NULL,32,1,'损益类 · 投资收益',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PL_09','营业利润','income','amount','元',2,'calc','calc',NULL,NULL,33,1,'损益类 · 营业利润',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PL_10','营业外收入','income','amount','元',2,'gl','none',NULL,NULL,34,1,'损益类 · 营业外收入',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PL_11','营业外支出','income','amount','元',2,'gl','none',NULL,NULL,35,1,'损益类 · 营业外支出',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PL_12','利润总额','income','amount','元',2,'calc','calc',NULL,NULL,36,1,'损益类 · 利润总额',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PL_13','所得税费用','income','amount','元',2,'gl','none',NULL,NULL,37,1,'损益类 · 所得税费用',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PL_14','净利润','income','amount','元',2,'calc','calc',NULL,NULL,38,1,'损益类 · 净利润',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PL_15','毛利率','income','rate','%',2,'calc','calc',NULL,NULL,39,1,'损益类 · 毛利率',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PL_16','净利率','income','rate','%',2,'calc','calc',NULL,NULL,40,1,'损益类 · 净利率',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PL_17','基本每股收益','income','amount','元/股',4,'calc','calc',NULL,NULL,41,1,'损益类 · 基本每股收益',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CF_01','销售商品提供劳务收到的现金','cashflow','amount','元',2,'gl','none',NULL,NULL,42,1,'现金流量类 · 销售商品提供劳务收到的现金',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CF_02','收到的税费返还','cashflow','amount','元',2,'gl','none',NULL,NULL,43,1,'现金流量类 · 收到的税费返还',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CF_03','购买商品接受劳务支付的现金','cashflow','amount','元',2,'gl','none',NULL,NULL,44,1,'现金流量类 · 购买商品接受劳务支付的现金',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CF_04','支付给职工的现金','cashflow','amount','元',2,'gl','none',NULL,NULL,45,1,'现金流量类 · 支付给职工的现金',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CF_05','支付的各项税费','cashflow','amount','元',2,'gl','none',NULL,NULL,46,1,'现金流量类 · 支付的各项税费',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CF_06','经营活动现金流量净额','cashflow','amount','元',2,'calc','calc',NULL,NULL,47,1,'现金流量类 · 经营活动现金流量净额',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CF_07','收回投资收到的现金','cashflow','amount','元',2,'gl','none',NULL,NULL,48,1,'现金流量类 · 收回投资收到的现金',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CF_08','购建固定资产支付的现金','cashflow','amount','元',2,'gl','none',NULL,NULL,49,1,'现金流量类 · 购建固定资产支付的现金',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CF_09','投资活动现金流量净额','cashflow','amount','元',2,'calc','calc',NULL,NULL,50,1,'现金流量类 · 投资活动现金流量净额',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CF_10','取得借款收到的现金','cashflow','amount','元',2,'gl','none',NULL,NULL,51,1,'现金流量类 · 取得借款收到的现金',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CF_11','偿还债务支付的现金','cashflow','amount','元',2,'gl','none',NULL,NULL,52,1,'现金流量类 · 偿还债务支付的现金',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CF_12','分配股利支付的现金','cashflow','amount','元',2,'gl','none',NULL,NULL,53,1,'现金流量类 · 分配股利支付的现金',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CF_13','筹资活动现金流量净额','cashflow','amount','元',2,'calc','calc',NULL,NULL,54,1,'现金流量类 · 筹资活动现金流量净额',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CF_14','现金及现金等价物净增加额','cashflow','amount','元',2,'calc','calc',NULL,NULL,55,1,'现金流量类 · 现金及现金等价物净增加额',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CF_15','期末现金及现金等价物余额','cashflow','amount','元',2,'calc','calc',NULL,NULL,56,1,'现金流量类 · 期末现金及现金等价物余额',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PD_01','产量','production','qty','件',0,'manual','none',NULL,NULL,57,1,'生产类 · 产量',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PD_02','产值','production','amount','元',2,'calc','calc',NULL,NULL,58,1,'生产类 · 产值',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PD_03','投料量','production','qty','吨',2,'manual','none',NULL,NULL,59,1,'生产类 · 投料量',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PD_04','单位产品成本','production','amount','元',2,'calc','calc',NULL,NULL,60,1,'生产类 · 单位产品成本',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PD_05','直接材料','production','amount','元',2,'gl','none',NULL,NULL,61,1,'生产类 · 直接材料',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PD_06','直接人工','production','amount','元',2,'gl','none',NULL,NULL,62,1,'生产类 · 直接人工',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PD_07','制造费用','production','amount','元',2,'gl','none',NULL,NULL,63,1,'生产类 · 制造费用',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PD_08','在产品数量','production','qty','件',0,'manual','none',NULL,NULL,64,1,'生产类 · 在产品数量',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PD_09','产成品数量','production','qty','件',0,'manual','none',NULL,NULL,65,1,'生产类 · 产成品数量',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PD_10','设备开工率','production','rate','%',2,'manual','none',NULL,NULL,66,1,'生产类 · 设备开工率',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PD_11','产能利用率','production','rate','%',2,'calc','calc',NULL,NULL,67,1,'生产类 · 产能利用率',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PD_12','良品率','production','rate','%',2,'manual','none',NULL,NULL,68,1,'生产类 · 良品率',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PD_13','单位工时','production','qty','工时',2,'manual','none',NULL,NULL,69,1,'生产类 · 单位工时',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('PD_14','能耗成本','production','amount','元',2,'gl','none',NULL,NULL,70,1,'生产类 · 能耗成本',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('SL_01','销售数量','sales','qty','件',0,'manual','none',NULL,NULL,71,1,'销售类 · 销售数量',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('SL_02','销售金额','sales','amount','元',2,'gl','none',NULL,NULL,72,1,'销售类 · 销售金额',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('SL_03','销售单价','sales','amount','元',2,'calc','calc',NULL,NULL,73,1,'销售类 · 销售单价',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('SL_04','销售退回','sales','amount','元',2,'gl','none',NULL,NULL,74,1,'销售类 · 销售退回',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('SL_05','销售折扣','sales','amount','元',2,'gl','none',NULL,NULL,75,1,'销售类 · 销售折扣',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('SL_06','销售净额','sales','amount','元',2,'calc','calc',NULL,NULL,76,1,'销售类 · 销售净额',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('SL_07','回款金额','sales','amount','元',2,'gl','none',NULL,NULL,77,1,'销售类 · 回款金额',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('SL_08','回款率','sales','rate','%',2,'calc','calc',NULL,NULL,78,1,'销售类 · 回款率',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('SL_09','客户数量','sales','qty','户',0,'manual','none',NULL,NULL,79,1,'销售类 · 客户数量',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('SL_10','新增客户数','sales','qty','户',0,'manual','none',NULL,NULL,80,1,'销售类 · 新增客户数',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('SL_11','市场占有率','sales','rate','%',2,'manual','none',NULL,NULL,81,1,'销售类 · 市场占有率',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('SL_12','订单数量','sales','qty','单',0,'manual','none',NULL,NULL,82,1,'销售类 · 订单数量',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('SL_13','平均客单价','sales','amount','元',2,'calc','calc',NULL,NULL,83,1,'销售类 · 平均客单价',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('SL_14','销售毛利','sales','amount','元',2,'calc','calc',NULL,NULL,84,1,'销售类 · 销售毛利',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CO_01','材料成本','cost','amount','元',2,'gl','none',NULL,NULL,85,1,'成本费用类 · 材料成本',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CO_02','人工成本','cost','amount','元',2,'gl','none',NULL,NULL,86,1,'成本费用类 · 人工成本',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CO_03','制造费用','cost','amount','元',2,'gl','none',NULL,NULL,87,1,'成本费用类 · 制造费用',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CO_04','期间费用','cost','amount','元',2,'gl','none',NULL,NULL,88,1,'成本费用类 · 期间费用',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CO_05','水电费','cost','amount','元',2,'gl','none',NULL,NULL,89,1,'成本费用类 · 水电费',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CO_06','折旧费','cost','amount','元',2,'gl','none',NULL,NULL,90,1,'成本费用类 · 折旧费',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CO_07','摊销费','cost','amount','元',2,'gl','none',NULL,NULL,91,1,'成本费用类 · 摊销费',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CO_08','差旅费','cost','amount','元',2,'gl','none',NULL,NULL,92,1,'成本费用类 · 差旅费',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CO_09','业务招待费','cost','amount','元',2,'gl','none',NULL,NULL,93,1,'成本费用类 · 业务招待费',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CO_10','单位成本','cost','amount','元',2,'calc','calc',NULL,NULL,94,1,'成本费用类 · 单位成本',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('CO_11','成本费用总额','cost','amount','元',2,'calc','calc',NULL,NULL,95,1,'成本费用类 · 成本费用总额',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('TX_01','应交增值税','tax','amount','元',2,'gl','none',NULL,NULL,96,1,'税务类 · 应交增值税',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('TX_02','销项税额','tax','amount','元',2,'gl','none',NULL,NULL,97,1,'税务类 · 销项税额',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('TX_03','进项税额','tax','amount','元',2,'gl','none',NULL,NULL,98,1,'税务类 · 进项税额',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('TX_04','应交企业所得税','tax','amount','元',2,'gl','none',NULL,NULL,99,1,'税务类 · 应交企业所得税',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('TX_05','应交城建税','tax','amount','元',2,'gl','none',NULL,NULL,100,1,'税务类 · 应交城建税',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('TX_06','教育费附加','tax','amount','元',2,'gl','none',NULL,NULL,101,1,'税务类 · 教育费附加',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('TX_07','应交印花税','tax','amount','元',2,'gl','none',NULL,NULL,102,1,'税务类 · 应交印花税',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('TX_08','税负率','tax','rate','%',2,'calc','calc',NULL,NULL,103,1,'税务类 · 税负率',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('TX_09','实际税率','tax','rate','%',2,'calc','calc',NULL,NULL,104,1,'税务类 · 实际税率',CURRENT_TIMESTAMP);
INSERT INTO cr_data_element (code,name,category_code,data_type,unit,decimals,value_source,formula_type,calc_formula,check_formula,sort_no,status,remark,create_time) VALUES ('TX_10','已缴税额','tax','amount','元',2,'gl','none',NULL,NULL,105,1,'税务类 · 已缴税额',CURRENT_TIMESTAMP);

-- 合计：7 大类 · 105 个数据元素
