-- =============================================
-- fico-db 合并组织架构字典 (cr_consol_org) —— 中国石油 (CNPC) 合并方案
--   由 gen_fico_cnpc_consol_org.py 生成，勿手改。parent_id 自分级树。
--   共 30 个组织节点；id 段 1001+（避开 CSCEC 示例）；consol_scheme='CNPC'。
--   覆盖：集团→上市平台→板块→油田/石化/销售分支 + 海外(USD)/合营/联营(权益法)/工程/金融。
-- 幂等：先 DELETE consol_scheme='CNPC' 再插入，可重复执行。
-- =============================================

DELETE FROM cr_consol_org WHERE consol_scheme = 'CNPC';
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1001,'CNPC','中国石油天然气集团有限公司','CNPC','group',NULL,'CNPC',1,0,'CNPC','full',100.0,100.0,'CNY',1,1,'集团总部/合并主体(母公司)',1,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1002,'PETROCHINA','中国石油天然气股份有限公司','CNPC','subgroup',1001,'CNPC.PETROCHINA',2,0,'PETROCHINA','full',86.35,86.35,'CNY',0,1,'上市平台(A股601857/H股00857)',2,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1003,'EP','勘探与生产板块','CNPC','subgroup',1002,'CNPC.PETROCHINA.EP',3,0,'EP','full',100.0,100.0,'CNY',0,1,'油气和新能源分部',3,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1004,'DAQING','大庆油田有限责任公司','CNPC','entity',1003,'CNPC.PETROCHINA.EP.DAQING',4,1,'DAQING','full',100.0,100.0,'CNY',0,1,'主力油田',4,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1005,'CHANGQING','长庆油田分公司','CNPC','branch',1003,'CNPC.PETROCHINA.EP.CHANGQING',4,1,'CHANGQING','full',100.0,100.0,'CNY',0,1,'鄂尔多斯盆地',5,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1006,'TARIM','塔里木油田分公司','CNPC','branch',1003,'CNPC.PETROCHINA.EP.TARIM',4,1,'TARIM','full',100.0,100.0,'CNY',0,1,'西部油气',6,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1007,'XINJIANG','新疆油田分公司','CNPC','branch',1003,'CNPC.PETROCHINA.EP.XINJIANG',4,1,'XINJIANG','full',100.0,100.0,'CNY',0,1,'准噶尔盆地',7,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1008,'SOUTHWEST','西南油气田分公司','CNPC','branch',1003,'CNPC.PETROCHINA.EP.SOUTHWEST',4,1,'SOUTHWEST','full',100.0,100.0,'CNY',0,1,'川渝天然气',8,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1009,'HUABEI','华北油田分公司','CNPC','branch',1003,'CNPC.PETROCHINA.EP.HUABEI',4,1,'HUABEI','full',100.0,100.0,'CNY',0,1,'冀中/二连',9,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1010,'RC','炼油化工与新材料板块','CNPC','subgroup',1002,'CNPC.PETROCHINA.RC',3,0,'RC','full',100.0,100.0,'CNY',0,1,'炼化分部',10,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1011,'DALIAN','大连石化分公司','CNPC','branch',1010,'CNPC.PETROCHINA.RC.DALIAN',4,1,'DALIAN','full',100.0,100.0,'CNY',0,1,'千万吨级炼厂',11,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1012,'LANZHOU','兰州石化分公司','CNPC','branch',1010,'CNPC.PETROCHINA.RC.LANZHOU',4,1,'LANZHOU','full',100.0,100.0,'CNY',0,1,'西部炼化基地',12,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1013,'DUSHANZI','独山子石化分公司','CNPC','branch',1010,'CNPC.PETROCHINA.RC.DUSHANZI',4,1,'DUSHANZI','full',100.0,100.0,'CNY',0,1,'炼化一体化',13,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1014,'GUANGDONG','广东石化有限责任公司','CNPC','entity',1010,'CNPC.PETROCHINA.RC.GUANGDONG',4,1,'GUANGDONG','full',100.0,100.0,'CNY',0,1,'2000万吨炼化一体化',14,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1015,'MK','销售板块','CNPC','subgroup',1002,'CNPC.PETROCHINA.MK',3,0,'MK','full',100.0,100.0,'CNY',0,1,'成品油/非油销售',15,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1016,'MK_HD','华东销售分公司','CNPC','branch',1015,'CNPC.PETROCHINA.MK.MK_HD',4,1,'MK_HD','full',100.0,100.0,'CNY',0,1,NULL,16,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1017,'MK_HB','华北销售分公司','CNPC','branch',1015,'CNPC.PETROCHINA.MK.MK_HB',4,1,'MK_HB','full',100.0,100.0,'CNY',0,1,NULL,17,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1018,'MK_HN','华南销售分公司','CNPC','branch',1015,'CNPC.PETROCHINA.MK.MK_HN',4,1,'MK_HN','full',100.0,100.0,'CNY',0,1,NULL,18,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1019,'MK_XN','西南销售分公司','CNPC','branch',1015,'CNPC.PETROCHINA.MK.MK_XN',4,1,'MK_XN','full',100.0,100.0,'CNY',0,1,NULL,19,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1020,'JV_BP','中油碧辟石油有限公司','CNPC','entity',1015,'CNPC.PETROCHINA.MK.JV_BP',4,1,'JV_BP','equity',49.0,49.0,'CNY',0,1,'与 BP 合营(权益法核算)',20,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1021,'KUNLUN','昆仑能源有限公司','CNPC','entity',1002,'CNPC.PETROCHINA.KUNLUN',3,1,'KUNLUN','full',54.38,54.38,'CNY',0,1,'港股00135;天然气终端(少数股东权益)',21,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1022,'CNPCINTL','中国石油国际勘探开发有限公司','CNPC','subgroup',1001,'CNPC.CNPCINTL',2,0,'CNPCINTL','full',100.0,100.0,'USD',0,1,'海外油气(中油国际);USD 折算',22,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1023,'CNPC_ME','中油国际(中东)有限公司','CNPC','entity',1022,'CNPC.CNPCINTL.CNPC_ME',3,1,'CNPC_ME','full',100.0,100.0,'USD',0,1,'中东区',23,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1024,'CNPC_CA','中油国际(中亚)有限公司','CNPC','entity',1022,'CNPC.CNPCINTL.CNPC_CA',3,1,'CNPC_CA','full',100.0,100.0,'USD',0,1,'中亚区',24,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1025,'CNPC_AM','中油国际(美洲)有限公司','CNPC','entity',1022,'CNPC.CNPCINTL.CNPC_AM',3,1,'CNPC_AM','full',100.0,100.0,'USD',0,1,'美洲区',25,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1026,'CPECC','中国石油工程建设有限公司','CNPC','entity',1001,'CNPC.CPECC',2,1,'CPECC','full',100.0,100.0,'CNY',0,1,'中油工程(601789)',26,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1027,'DRILLING','中国石油集团钻探工程有限公司','CNPC','entity',1001,'CNPC.DRILLING',2,1,'DRILLING','full',100.0,100.0,'CNY',0,1,'钻探工程服务',27,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1028,'CPLOG','中国石油集团测井有限公司','CNPC','entity',1001,'CNPC.CPLOG',2,1,'CPLOG','full',100.0,100.0,'CNY',0,1,'测井技术服务',28,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1029,'CAPITAL','中国石油集团资本股份有限公司','CNPC','entity',1001,'CNPC.CAPITAL',2,1,'CAPITAL','full',76.5,76.5,'CNY',0,1,'金融板块(少数股东权益)',29,1,CURRENT_TIMESTAMP);
INSERT INTO cr_consol_org (id,code,name,consol_scheme,org_type,parent_id,full_path,level_no,is_leaf,entity_code,consol_method,ownership_pct,voting_pct,consol_currency,is_parent,offset_flag,remark,sort_no,status,create_time) VALUES (1030,'PIPECHINA','国家石油天然气管网集团有限公司','CNPC','entity',1001,'CNPC.PIPECHINA',2,1,'PIPECHINA','equity',29.9,29.9,'CNY',0,1,'联营企业(国家管网)权益法核算',30,1,CURRENT_TIMESTAMP);

-- 节点合计 30；根 1（CNPC）；末级(叶) 24 个。
