[package]
name = "cmx-metadata"
version.workspace = true
edition.workspace = true

[dependencies]
cmx-core = { workspace = true }
cmx-database = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
regex = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
# sea-query: SQL 构建工具
sea-query = { workspace = true }
# sea-query-binder: SQL 参数绑定工具
sea-query-binder = { workspace = true }
async-trait = { workspace = true }
# csv: CSV 文件解析
csv = "1.3"