[package]
name = "cmx-wasmdemo"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
# ============================================
# Extism PDK
# ============================================
extism-pdk = "1.4.1"

# ============================================
# CMX 插件 SDK
# ============================================
cmx-plugin-sdk = { path = "../cmx-plugin-sdk" }

# ============================================
# 序列化
# ============================================
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
